import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./navbar/page";
import Footer from "./footer";
import Feature from "./features/page";
import { CartProvider } from "@/app/context/Cart"; // Import CartProvider




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <CartProvider> {/* Ensure everything is inside CartProvider */}
          <Navbar />
          {children}
          <Feature />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}

